module.exports = function(grunt) {
    "use strict";
  
    grunt.initConfig({

      env : {
        dev : {
          src : "./environment/dev.json",
        },
        prod : {
          src : "./environment/prod.json",
        },
        test : {
          src : "./environment/test.json",
        },
      },

      concurrent: {
        dev: {
          tasks: ['nodemon:debug', 'watch'],
          options: {
            logConcurrentOutput: true
          }
        }
      },

      nodemon: {
        debug: {
          script: './bin/www',
          options: {
            nodeArgs: ['--debug'],
          }
        },
        run: {
          script: './bin/www',
          options: {
            nodeArgs: [],
          }
        },
      },
      
      ts: {
        app: {
          files: [{
            src: ["./src/\*\*/\*.ts", "!./src/.baseDir.ts", "!./src/_all.d.ts", "!./dist/\*\*", "!./test/\*\*"], /*, "!./src/.baseDir.ts", "!./src/_all.d.ts", "!./dist/\*\*"*/
            dest: "./dist"
          },],
          tsconfig: true
        },

        test: {
          files: [{
            src: ["./src/\*\*/\*.ts", "!./src/.baseDir.ts", "!./src/_all.d.ts", './test/**/*.ts', "!dist/\*\*"],
            dest: "./test/dist"
          },],
          tsconfig: true
        }
      },
      
      tslint: {
        options: {
          configuration: "tslint.json"
        },
        files: {
          src: [
            "./src/\*\*/\*.ts",
            "!./src/_autogenerated\*/\*\*/\*.ts"
          ]
        }
      },

      watch: {
        ts: {
          files: ["js/src/\*\*/\*.ts", "src/\*\*/\*.ts", "src/\*\*/\*.jade", "src/\*\*/\*.css"],
          tasks: ["ts:app", "tslint", "copy"]
        }
      },

      copy: {
        static: {
          expand: true,
          cwd: './src/static',
          src: ['**'],
          dest: './dist/static'
        },
        template:{
          expand: true,
          cwd: './src/tasks',
          src: ['**/*.njk'],
          dest: './dist/tasks'
        }
      },

      mochaTest: {
        test: {
          options: {
            log: true,
            run: true
          },
          src: ['./test/**/*.js']
        },
      },

      generateHistoryModel:{
        make:
        {
          files:[{
          expand: true,
          cwd: './src/models',
          src: ['**/*.ts'],
          dest: './src/_autogenerated_historymodels',
        }],
        oneFile:false
        }
      },
      
      generateViewModel:{
        make:
        {
          files:[{
          expand: true,
          cwd: './src/models',
          src: ['**/*.ts'],
          dest: './src/_autogenerated_viewmodels',
        }],
        oneFile:false
        }
      },
    });
  
    grunt.loadNpmTasks("grunt-contrib-watch");
    grunt.loadNpmTasks('grunt-nodemon');
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.loadNpmTasks("grunt-ts");
    grunt.loadNpmTasks('grunt-concurrent');
    grunt.loadNpmTasks("grunt-tslint");
    grunt.loadNpmTasks('grunt-env');
    grunt.loadNpmTasks('grunt-mocha-test');
    grunt.loadNpmTasks('grunt-generate-view-model');
    grunt.loadNpmTasks('grunt-generate-history-model');
    
  
    grunt.registerTask("default", [
      "nodemon:run"
    ]);


    grunt.registerTask("debugVS", [
      "env:prod", "build", "nodemon:debug"
    ]);

    grunt.registerTask("debug", [
      "env:dev", "concurrent"
    ]);

    grunt.registerTask("release", [
      "env:prod", "concurrent"
    ]);

    grunt.registerTask("test", [
      "env:test", "ts:test",  "mochaTest"
    ]);

    grunt.registerTask("build", [
      "ts:app", "tslint", "copy"
    ]);

    grunt.registerTask("history", ["generateHistoryModel", "generateViewModel"]);
  };